### ISSUE TITLE
any luck on view distance ?

### ISSUE THREAD

**Issue by Gamedev1909** [MrCheeze/botw-tools#1]
so we want to make the view distance longer is there anyway you can search for a way?

**Comment by MrCheeze** [comment]
If I understand you correctly, I suspect that would require modifying the game engine, rather than just tuning some parameter. In any case it's beyond the scope of what I'm looking into here.

**Comment by Gamedev1909** [comment]
no i want to edit the xml files you have which controls most of the distance i want to change for each area

**Comment by MrCheeze** [comment]
Okay, I think I don't actually understand what it is you're trying to do at all. Could you elaborate a bit?

**Comment by Gamedev1909** [comment]
the grass render distance is a bit short same with tree's and plants what we want to do is boost that so the world looks more full on Cemu we just have no idea where to start

**Comment by MrCheeze** [comment]
I believe that would require an engine modification, yeah. Grass is a special case in the game engine.

**Comment by Gamedev1909** [comment]
dam
well thanks
