### ISSUE TITLE
Question about BotW height map

### ISSUE THREAD

**Issue by TriforceCreeper** [MrCheeze/botw-tools#12]
Sorry if this is the wrong place to ask this, I'm not too familiar with using GitHub, but after seeing the height map for Breath of the Wild in this repo, I'm curious to know where I might be able to find something similar for Twilight Princess?

**Comment by MrCheeze** [comment]
Generally, most games will not have explicit heightmap data - the world will just be generically 3D modelled. BotW does it to make having a very large open world more efficient.
