### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by JD2542** [MrCheeze/botw-tools#3]
Can you make a README explaining how to use it and how it works or maybe a video

**Comment by MrCheeze** [comment]
This is not so much a single tool with a single purpose, as it is various random tools I've come up with during my datamining efforts. You can experiment around a bit, or if you just want the results you can check botw-object-map or https://pastebin.com/u/MrCheeze

**Comment by lordneeko** [comment]
i found the grudge actor packs for the castle
Grudge_HyruleCastle.sbactorpack
Grudge_HyruleCastle.sesetlist

I deleted them and re-launched Cemu...but all the grudge is still there...do you have to wipe out shader caches to force it to reload from the files?

**Comment by MrCheeze** [comment]
I'm not sure whether just deleting actor packs works or not... but there's more malice actors than just that one. Try some of these, especially the MergedGrudge ones.

EfLocater_GrudgeRib_L
EfLocater_GrudgeRib_LL
EfLocater_GrudgeRib_M
EfLocater_GrudgeSolid_L
EfLocater_GrudgeSolid_LL
EfLocater_GrudgeSolid_LLL
EfLocater_GrudgeSolid_LL_02
EfLocater_GrudgeSolid_L_02
EfLocater_GrudgeSolid_M
EfLocater_GrudgeSolid_M_02
Naydra — Enemy_Dragon_Grudge
Naydra — Enemy_Dragon_Grudge_Far
Grudge_HyruleCastle
MergedGrudge_B-3_0
MergedGrudge_B-3_1
MergedGrudge_B-3_2
MergedGrudge_B-4_0
MergedGrudge_B-4_1
MergedGrudge_B-4_2
MergedGrudge_D-6_0
MergedGrudge_D-8_0
MergedGrudge_E-1_1
MergedGrudge_E-4_0-BB
MergedGrudge_E-4_0-BB_Far
MergedGrudge_E-4_0-BC
MergedGrudge_E-4_0-BC_Far
MergedGrudge_E-4_0-CA
MergedGrudge_E-4_0-CA_Far
MergedGrudge_E-4_0-CB
MergedGrudge_E-4_0-CB_Far
MergedGrudge_E-4_0-CC
MergedGrudge_E-4_0-CC_Far
MergedGrudge_E-4_0-DA
MergedGrudge_E-4_0-DA_Far
MergedGrudge_E-4_0-DB
MergedGrudge_E-4_0-DB_Far
MergedGrudge_E-4_0-DC
MergedGrudge_E-4_0-DC_Far
MergedGrudge_E-4_1
MergedGrudge_E-4_10
MergedGrudge_E-4_11
MergedGrudge_E-4_12
MergedGrudge_E-4_13
MergedGrudge_E-4_14
MergedGrudge_E-4_15
MergedGrudge_E-4_16
MergedGrudge_E-4_17
MergedGrudge_E-4_18
MergedGrudge_E-4_19
MergedGrudge_E-4_2
MergedGrudge_E-4_20
MergedGrudge_E-4_3
MergedGrudge_E-4_4
MergedGrudge_E-4_5
MergedGrudge_E-4_6
MergedGrudge_E-4_7
MergedGrudge_E-4_8
MergedGrudge_E-4_9
MergedGrudge_F-4_0
MergedGrudge_F-5_0
MergedGrudge_I-3_0
MergedGrudge_I-3_1
TwnObj_GanonGrudgeSolid_Eyeball_A_01
TwnObj_GanonGrudgeSolid_Generator_A_01
TwnObj_HyruleCastle_GanonGrudge_A_01
TwnObj_HyruleCastle_GanonGrudge_A_01_Far

**Comment by lordneeko** [comment]
Oh wow..those didn't even show up when I searched my folders. You're
probably right. I bet maybe all I deleted was some of the Malice in the
castle. I'm going to go extreme and just get rid of all of it and see what
happens.

Thanks!
