### ISSUE TITLE
Update with newest dlc content

### ISSUE THREAD

**Issue by Crementif** [MrCheeze/botw-tools#6]
The [BotW modding community](https://discord.gg/sZ36p8) would really like to see this list being updated with the latest game update+dlc as it's a really helpful resource for multiple mods you might've seen lately for BotW. I'm not sure what the steps would be to update the list on my own, but it would be very handy to have it updated. Thanks for the useful resource!

**Comment by MrCheeze** [comment]
A little late, but finally got this done. :) Use it as you will.

**Comment by Crementif** [comment]
thanks a bunch dude! Will share the news 👍
