### ISSUE TITLE
How to remove Malice

### ISSUE THREAD

**Issue by lordneeko** [MrCheeze/botw-tools#9]
I'm trying to figure out if there is a game file somewhere that contains the "Malice" module. You know, the purple flowy stuff.

I'm trying to see if it is possible to remove or replace it.
Thanks

**Comment by MrCheeze** [comment]
Internally the game refers to it not as Malice, but as "Grudge". With that in mind you should be able to find all the actors that involve it.

**Comment by lordneeko** [comment]
excellent thanks.
